import { Person } from "./Person";
import type {
  About,
  Banner,
  Feature,
  FeatureCards,
  FeatureList,
  Footer,
  FooterItem,
  FrequentlyAskedQuestionItem,
  FrequentlyAskedQuestions,
  Hero,
  Highlights,
  Member,
  Navbar,
  NavbarItem,
  Newsletter,
  Partner,
  Partners,
  Pricing,
  PricingCard,
  Social,
  Stat,
  Team,
  Testimonial,
  Testimonials,
} from "./WebsiteConfig";

export type {
  About,
  Banner,
  Feature,
  FeatureCards,
  FeatureList,
  Footer,
  FooterItem,
  FrequentlyAskedQuestionItem,
  FrequentlyAskedQuestions, Hero, Highlights,
  Member,
  Navbar,
  NavbarItem,
  Newsletter,
  Partner,
  Partners, Person, Pricing,
  PricingCard,
  Social,
  Stat,
  Team,
  Testimonial, Testimonials
};

